/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSqlRouteImport } from './routes/_app/sql'
import { Route as AppPerformanceRouteImport } from './routes/_app/performance'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppEditorRouteImport } from './routes/_app/editor'
import { Route as AppDatabaseRouteImport } from './routes/_app/database'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSqlRoute = AppSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorRoute = AppEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppRoute,
} as any)
const AppDatabaseRoute = AppDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/database': typeof AppDatabaseRoute
  '/editor': typeof AppEditorRoute
  '/overview': typeof AppOverviewRoute
  '/performance': typeof AppPerformanceRoute
  '/sql': typeof AppSqlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/database': typeof AppDatabaseRoute
  '/editor': typeof AppEditorRoute
  '/overview': typeof AppOverviewRoute
  '/performance': typeof AppPerformanceRoute
  '/sql': typeof AppSqlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/database': typeof AppDatabaseRoute
  '/_app/editor': typeof AppEditorRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/sql': typeof AppSqlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/database'
    | '/editor'
    | '/overview'
    | '/performance'
    | '/sql'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/database'
    | '/editor'
    | '/overview'
    | '/performance'
    | '/sql'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/database'
    | '/_app/editor'
    | '/_app/overview'
    | '/_app/performance'
    | '/_app/sql'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sql': {
      id: '/_app/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof AppSqlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editor': {
      id: '/_app/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AppEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/database': {
      id: '/_app/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AppDatabaseRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDatabaseRoute: typeof AppDatabaseRoute
  AppEditorRoute: typeof AppEditorRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppSqlRoute: typeof AppSqlRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDatabaseRoute: AppDatabaseRoute,
  AppEditorRoute: AppEditorRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppSqlRoute: AppSqlRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
